name: Foxandbox movie recommendation app

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --max-complexity=20 --max-line-length=100 --statistics
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint `find . | grep '.*.py$'`
